defaults:
    - celeba_gan
    - _self_
trainer:
    max_epochs: 30
    log_every_n_steps: 1
    check_val_every_n_epoch: 1
    limit_train_batches: 5000
trainable:
    losses:
        -
            _target_: src.losses.PerceptualDistanceSquaredNormalizedMTopDivYXLoss
            denoising_fraction: 1
            dimension: 0
datamodule:
    batch_size: 32