defaults:
    - four_gaussians_wgan_gp_mtd_xy
    - _self_
trainable:
    losses:
        -
            _target_: src.losses.PerceptualDistanceSquaredNormalizedMTopDivYXLoss
        -
            _target_: src.losses.MTopDivYXLoss
            dimension: 0