defaults:
  - gan
losses:
  - _target_: src.losses.WassersteinGPGANLoss
    discriminator:
      _target_: src.models.MLPDiscriminator
      input_dim: 2
      hidden_dim: 16
      num_hidden_layers: 2
      sigmoid: false