defaults:
    - celeba_gan
    - _self_
trainer:
    max_epochs: 30
    log_every_n_steps: 1
    check_val_every_n_epoch: 5
trainable:
    losses:
        -
            _target_: src.losses.SquaredNormalizedMTopDivYXLoss
            dimension: 0
        -
            _target_: src.losses.SquaredNormalizedMTopDivXYLoss
            dimension: 0
        -
            _target_: src.losses.StandardGANLoss
            discriminator:
                _target_: src.models.ConvolutionalDiscriminator
                channels: 3
                hidden_dim: 64
                sigmoid: true