defaults:
    - four_gaussians_wgan_gp_mtd_xy
    - _self_
trainable:
    losses:
        -
            _target_: src.losses.WassersteinGPGANLoss
            discriminator:
                _target_: src.models.MLPDiscriminator
                input_dim: 2
                hidden_dim: 16
                num_hidden_layers: 2
                sigmoid: false
        -
            _target_: src.losses.MTopDivYXLoss
            dimension: 0
datamodule:
    batch_size: 32