logger:
    project: "topogans"
    offline: true
    entity: "penchekrak"
trainer:
    limit_val_batches: 5
    max_epochs: 300
    log_every_n_steps: 1
    check_val_every_n_epoch: 15
    accelerator: 'cuda'
    callbacks:
        - _target_: src.callbacks.PlotSampledImages
        - _target_: src.callbacks.GC
        - _target_: src.callbacks.MNISTClassDistributionCallback
          samples_count: 2000
        - _target_: src.callbacks.NDBCallback
          feature_extractor: mnist_extractor
          samples_count: 2000
trainable:
    _target_: src.trainable.Trainable

    generator:
        _target_: src.models.ConvolutionalGenerator
        latent_dim: 100
        hidden_dim: 64
        channels: 1

    losses:
        -
            _target_: src.losses.WassersteinGPGANLoss
            discriminator:
                _target_: src.models.ConvolutionalDiscriminator
                channels: 1
                hidden_dim: 64
                sigmoid: false

    optimizer_config:
        generator:
            optimizer:
                _target_: torch.optim.Adam
                _partial_: True
                lr: 0.0002
                betas:
                    - 0.5
                    - 0.999
            frequency: 1
        losses:
            optimizer:
                _target_: torch.optim.Adam
                _partial_: True
                lr: 0.0002
                betas:
                    - 0.5
                    - 0.999
            frequency: 1
datamodule:
    _target_: src.datasets.MNISTDataModule
    batch_size: 512
    data_dir: spiridonov/TopReg/data/mnist/MNIST