defaults:
    - mnist_gan
    - _self_
trainer:
    max_epochs: 60
    check_val_every_n_epoch: 10
trainable:
    losses:
        -
            _target_: src.losses.MTopDivYXLoss
            dimension: 0
